spring:
  application:
    name: tableLink

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${SCHEMA_NAME}
    username: root
    password: ${LOCAL_DB_PW}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  logging:
    level:
      org:
        hibernate:
          dialect: MySQL8Dialect # MySQL 8 Dialect 설정
          type:
            descriptor:
              sql:
                BasicBinder: TRACE # Hibernate 파라미터 바인딩 로그 출력

jwt:
  secret: ${SECRET_KEY}
  expiration-time: ${EXPIRATION_TIME} # 1시간: 1 * 60 * 60 * 1000 = 3600000
  refresh-expiration-time: ${REFRESH_EXPIATION_TIME} # 3시간: 3 * 60 * 60 * 1000 = 3600000

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 알파벳 순으로 정렬
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴


